distributed.nanny - INFO -         Start Nanny at: 'tcp://172.20.5.205:35777'
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home/juliec/miniconda3/envs/mti_nma_ms/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/juliec/miniconda3/envs/mti_nma_ms/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/juliec/miniconda3/envs/mti_nma_ms/lib/python3.7/site-packages/distributed/process.py", line 191, in _run
    target(*args, **kwargs)
  File "/home/juliec/miniconda3/envs/mti_nma_ms/lib/python3.7/site-packages/distributed/nanny.py", line 672, in _run
    worker = Worker(**worker_kwargs)
  File "/home/juliec/miniconda3/envs/mti_nma_ms/lib/python3.7/site-packages/distributed/worker.py", line 505, in __init__
    self._workspace = WorkSpace(os.path.abspath(local_directory))
  File "/home/juliec/miniconda3/envs/mti_nma_ms/lib/python3.7/site-packages/distributed/diskutils.py", line 118, in __init__
    self._init_workspace()
  File "/home/juliec/miniconda3/envs/mti_nma_ms/lib/python3.7/site-packages/distributed/diskutils.py", line 124, in _init_workspace
    os.mkdir(self.base_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/juliec/.dask_logs/mti_nma/2020-03-19T11:41:47'
distributed.nanny - INFO - Worker process 5368 exited with status 1
distributed.nanny - INFO - Closing Nanny at 'tcp://172.20.5.205:35777'
distributed.dask_worker - INFO - End worker
